#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ClickUp Report Uploader
Uploads analysis reports (report.md) to ClickUp as comments
"""

import os
import sys
import json
import argparse
import requests
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

CLICKUP_API_KEY = os.getenv("CLICKUP_API_KEY")
if not CLICKUP_API_KEY:
    print("Error: CLICKUP_API_KEY not found in .env file")
    sys.exit(1)

# Load config
with open("config.json", "r", encoding="utf-8") as f:
    config = json.load(f)

BASE_URL = config["clickup"]["base_url"]
TASKS_DIR = config["tasks_dir"]

HEADERS = {
    "Authorization": CLICKUP_API_KEY,
    "Content-Type": "application/json"
}


def upload_comment(task_id, comment_text):
    """Upload comment to ClickUp task"""
    url = f"{BASE_URL}/task/{task_id}/comment"

    payload = {
        "comment_text": comment_text
    }

    print(f"Uploading analysis report to task: {task_id}")
    response = requests.post(url, headers=HEADERS, json=payload)

    if response.status_code != 200:
        print(f"Error: Failed to upload comment to task {task_id}")
        print(f"Status: {response.status_code}")
        print(f"Response: {response.text}")
        return False

    print("✓ Report uploaded successfully!")
    return True


def read_report(task_id):
    """Read analysis report from local storage"""
    report_file = Path(TASKS_DIR) / task_id / "report.md"

    if not report_file.exists():
        print(f"Error: Report file not found: {report_file}")
        print("Run analyze.py first to generate the report")
        sys.exit(1)

    with open(report_file, "r", encoding="utf-8") as f:
        return f.read()


def main():
    parser = argparse.ArgumentParser(description="Upload analysis reports to ClickUp")
    parser.add_argument("--task-id", required=True, help="Task ID to upload report to")
    parser.add_argument("--dry-run", action="store_true", help="Preview without uploading")

    args = parser.parse_args()

    print(f"Reading report for task: {args.task_id}")

    # Read report
    report_content = read_report(args.task_id)

    # Add header
    upload_content = f"## 🤖 Claude AI 분석 보고서\n\n{report_content}\n\n---\n*Generated by [Claude Code Issue Analysis Bot](https://github.com/anthropics/claude-code)*"

    if args.dry_run:
        print("\n" + "="*60)
        print("DRY RUN - Preview of content to upload:")
        print("="*60)
        print(upload_content)
        print("="*60)
        print("\nRun without --dry-run to actually upload")
        return

    # Upload to ClickUp
    success = upload_comment(args.task_id, upload_content)

    if success:
        print(f"\n✓ Report uploaded to ClickUp task: {args.task_id}")
        print(f"  View at: https://app.clickup.com/t/{args.task_id}")
    else:
        print("\n✗ Upload failed")
        sys.exit(1)


if __name__ == "__main__":
    main()
